# Generated by Django 2.2 on 2020-03-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoreadsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='alias',
            field=models.CharField(default=2, max_length=45),
            preserve_default=False,
        ),
    ]
