# Generated by Django 2.2 on 2020-03-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoreadsapp', '0002_login_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='alias',
            field=models.CharField(default=models.CharField(max_length=45), max_length=45),
        ),
    ]
