# Generated by Django 2.2 on 2020-03-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoreadsapp', '0003_auto_20200321_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='alias',
            field=models.CharField(default='first_name', max_length=45),
        ),
    ]
