# Generated by Django 2.2 on 2020-03-21 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagess', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='loginapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='loginapp.Login')),
                ('messages', models.ManyToManyField(related_name='comments', to='wallapp.Message')),
            ],
        ),
    ]
