# Generated by Django 2.2 on 2020-03-21 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='logged',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='loginapp.Login'),
        ),
    ]
